LOAD DATA INFILE "{SECURE_PRIV_PATH}/census2021-ts001-oa.csv"
INTO TABLE ts001
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "{SECURE_PRIV_PATH}/census2021-ts007a-oa.csv"
INTO TABLE ts007a
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "{SECURE_PRIV_PATH}/census2021-ts061-oa.csv"
INTO TABLE ts061
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "{SECURE_PRIV_PATH}/census2021-ts062-oa.csv"
INTO TABLE ts062
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;